model:
  value: "MLPRegressionNet 2nd Try"
hidden_layers:
  value: [256, 128, 64, 32]
dropout:
  value: 0.0
batch_norm:
  value: false
activation:
  value: "relu"
lr:
  value: 0.001
weight_decay:
  value: 0.0
loss:
  value: "MSELoss"
target_transform:
  value: "log1p(frp)"
epochs:
  value: 25
batch_size:
  value: 256
seed:
  value: 42
MAE:
  value: 12.738304138183594
RMSE:
  value: 31.787868234509393
R2:
  value: 0.05813199281692505
test_loss_log_scale:
  value: 0.6758954112451793
best_epoch:
  value: 25
best_val_loss:
  value: 0.6727678010740746
