_wandb:
    value:
        cli_version: 0.27.2
        e:
            6tqv5xgi3httjb3lc755aushczaxuk3k:
                codePath: wildfire_image_classification.ipynb
                colab: https://colab.research.google.com/notebook#fileId=12iKsHyfBxLsiMx2uxtECkFOW0MkeoQIc
                cpu_count: 1
                cpu_count_logical: 2
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "120942624768"
                        used: "50814238720"
                email: dmshukakidze@mail.ru
                executable: /usr/bin/python3
                gpu: Tesla T4
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 2560
                      memoryTotal: "16106127360"
                      name: Tesla T4
                      uuid: GPU-23d9cff6-1705-e16c-7959-cf8716058331
                host: fd4ae10bfb31
                memory:
                    total: "13605822464"
                os: Linux-6.6.122+-x86_64-with-glibc2.35
                program: wildfire_image_classification.ipynb
                python: CPython 3.12.13
                root: /content
                startedAt: "2026-06-14T19:03:34.157066Z"
                writerId: 6tqv5xgi3httjb3lc755aushczaxuk3k
        m: []
        python_version: 3.12.13
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 1
                - 2
                - 13
                - 16
                - 62
            "4": 3.12.13
            "5": 0.27.2
            "8":
                - 1
                - 12
            "10":
                - 20
            "12": 0.27.2
            "13": linux-x86_64
activation:
    value: relu
adaptive_pooling:
    value:
        - 7
        - 7
architecture:
    value: improvedcnn
batch_norm:
    value: true
channels:
    value:
        - 32
        - 64
        - 128
classes:
    value:
        - fire
        - nofire
conv_blocks:
    value: 3
conv_per_block:
    value: 1
dropout:
    value: 0.3
entity:
    value: dmshukakidze-hse-university
hidden_size:
    value: 256
image_size:
    value: 224
lr:
    value: 0.0003
num_epochs:
    value: 10
num_workers:
    value: 0
pooling:
    value: maxpool2d
project:
    value: wildfire_image_classification
seed:
    value: 42
selection_metric:
    value: val_f1_fire
test_batch_size:
    value: 32
train_batch_size:
    value: 32
val_batch_size:
    value: 32
wandb:
    value: true
